name: ACME-KeyboardMarathon
abstract: How far have your fingers ran?
author: Phil Pollard <bennie@cpan.org>
version: VERSIONTAG
version_from: lib/ACME/LeyboardMarathon.pm
license: perl
distribution_type: module
generated_by: Phil Pollard <bennie@cpan.org>
