name:         ACME-KeyboardMarathon
version:      VERSIONTAG
version_from: lib/ACME/LeyboardMarathon.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
